imports:
    - behat.common.yml
default:
  extensions:
    Behat\MinkExtension:
      selenium2:
        wd_host: http://localhost:4444/wd/hub
        capabilities: { "browser": "chrome", "version": "*", 'chrome': {'switches':['--start-maximized', "--headless", "--disable-gpu"]}}
      javascript_session: selenium2
      browser_name: 'chrome'
      base_url: http://127.0.0.1:8888
      files_path: './profiles/openasu/modules/panopoly/panopoly_test/behat'
    Drupal\DrupalExtension:
      drush:
        root: "/home/travis/build/ctestama/webspark-drops-drupal7"
      drupal:
        drupal_root: "/home/travis/build/ctestama/webspark-drops-drupal7"

      # Look in the profile modules directory and pull in module subcontexts.
      subcontexts:
        paths:
          - "/home/travis/build/ctestama/webspark-drops-drupal7/profiles/openasu/modules/panopoly/panopoly_test"